In [29]:
#importing the importing Libraries.
#pandas is used to create a table.
#numpy is used for matrix manupulation its playing with number.
import pandas as pd
import numpy as np

In [3]:
#importing the datasets
Technical_skills = pd.read_csv('Example_Technical_Skills.csv')
Raw_skills = pd.read_csv('Raw_Skills_Dataset.csv')

In [4]:
Technical_skills

                         Technology Skills
0                      SAP Fiori Developer
1    Oracle Instance Management & Strategy
2             Boomi Master Data Management
3    Digital Manufacturing on Cloud ( DMC)
4                                   DevOps
..                                     ...
974        Oracle Cloud Revenue Management
975       Oracle EBS Grid Contral Mgt Pack
976         Amazon Elastic MapReduce (EMR)
977                            Apache Kudu
978                             Oracle ESB

[979 rows x 1 columns]

In [6]:
#shape is used for knowing how many rows and coloum are present
Technical_skills.shape

(979, 1)

In [7]:
#info is used for knowing is there null value are present or not and its also tells about the datatype
Technical_skills.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 979 entries, 0 to 978
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Technology Skills  979 non-null    object
dtypes: object(1)
memory usage: 7.8+ KB

In [8]:
#describe tells about all statistics values
Technical_skills.describe()

       Technology Skills
count                979
unique               897
top          DEC - Other
freq                   3

In [9]:
#head gives the top values
Technical_skills.head()

                       Technology Skills
0                    SAP Fiori Developer
1  Oracle Instance Management & Strategy
2           Boomi Master Data Management
3  Digital Manufacturing on Cloud ( DMC)
4                                 DevOps

In [10]:
Raw_skills.shape

(34116, 1)

In [11]:
Raw_skills.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34116 entries, 0 to 34115
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   RAW DATA  34116 non-null  object
dtypes: object(1)
memory usage: 266.7+ KB

In [12]:
Raw_skills.describe()

       RAW DATA
count     34116
unique    15677
top      Python
freq        272

In [13]:
Raw_skills.head()

          RAW DATA
0         What ifs
1        seniority
2      familiarity
3  functionalities
4          Lambdas

In [15]:
#rename the folder
Raw_skills.rename(columns = {'RAW DATA':'Technology_Skills'}, inplace = True)

In [16]:
Technical_skills.rename(columns = {'Technology Skills':'Technology_Skills'}, inplace=True)

In [17]:
Raw_skills

                                   Technology_Skills
0                                           What ifs
1                                          seniority
2                                        familiarity
3                                    functionalities
4                                            Lambdas
...                                              ...
34111                                    negotiation
34112                                      deadlines
34113  Self-motivated, enthusiastic and strong drive
34114                                    negotiation
34115                                      deadlines

[34116 rows x 1 columns]

In [18]:
Technical_skills

                         Technology_Skills
0                      SAP Fiori Developer
1    Oracle Instance Management & Strategy
2             Boomi Master Data Management
3    Digital Manufacturing on Cloud ( DMC)
4                                   DevOps
..                                     ...
974        Oracle Cloud Revenue Management
975       Oracle EBS Grid Contral Mgt Pack
976         Amazon Elastic MapReduce (EMR)
977                            Apache Kudu
978                             Oracle ESB

[979 rows x 1 columns]

In [20]:
#merging both of the datasets
dataset = Raw_skills.merge(Technical_skills, how = 'inner' ,indicator=False)

In [21]:
dataset

    Technology_Skills
0               MySQL
1               MySQL
2               MySQL
3               MySQL
4               MySQL
..                ...
317      Apache Oozie
318    Octopus Deploy
319    Octopus Deploy
320    Octopus Deploy
321          SAS Base

[322 rows x 1 columns]

In [22]:
#droping the null values
dataset.drop_duplicates(subset ="Technology_Skills", inplace = True)

In [23]:
dataset

              Technology_Skills
0                         MySQL
114                        SCSS
119                         EAC
120                      DevOps
167                   OpenShift
175                      GitHub
204                    NetSuite
206                   Bitbucket
216                    Ethereum
227                      Kotlin
255                        Bash
267                         FTP
271                   OneStream
272                      Consul
277                   Force.com
279               Amazon Lambda
280                      Radius
281                        Gulp
284      Guidewire PolicyCenter
285             Adobe Photoshop
287                     Eclipse
291                     Phantom
292                     Magento
295  Microsoft Azure Networking
296                    ActiveMQ
305                  SAP Lumira
306         SAP Analytics Cloud
308                     PostGIS
312                     SAS JMP
313                       NuGet
314                         DRM
315        SAS Enterprise Guide
316                     Katalon
317                Apache Oozie
318              Octopus Deploy
321                    SAS Base

In [24]:
dataset.shape

(36, 1)

In [25]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36 entries, 0 to 321
Data columns (total 1 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Technology_Skills  36 non-null     object
dtypes: object(1)
memory usage: 576.0+ bytes

In [28]:
#isnull is used for knowing is any null is prsent or not and sum is used for sum all the null values in this there is no any null value so is showing 0
dataset.isnull().sum()

Technology_Skills    0
dtype: int64

In [35]:
#importing the datasets for nltk and cleaning the datasets
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
raw = []
for i in range(0, 34116):
  cell = re.sub('[^a-zA-Z]', ' ', Raw_skills['Technology_Skills'][i])
  cell = cell.lower()
  cell = cell.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  cell = [ps.stem(word) for word in cell if not word in set(all_stopwords)]
  cell = ' '.join(cell)
  raw.append(cell)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\anand\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [39]:
#creating the train data
train_set = []
for i in range(0, 979):
  cell = re.sub('[^a-zA-Z]', ' ', Technical_skills['Technology_Skills'][i])
  cell = cell.lower()
  cell = cell.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  cell = [ps.stem(word) for word in cell if not word in set(all_stopwords)]
  cell = ' '.join(cell)
  train_set.append(cell)

In [70]:
#importing the CountVectorizer from the sKlearn library,and countVector are used for tokenize the sentence
from sklearn.feature_extraction.text import CountVectorizer
count_vec = CountVectorizer(max_features = 1500)
X = count_vec.fit_transform(train_set).toarray()
X_test = count_vec.transform(raw).toarray()
y = np.ones((979,))

In [71]:
#importing the gaussian naive bayes classifier
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X, y)

GaussianNB()

In [72]:
#predect the value
select = classifier.predict(X_test)

In [73]:
Info=[]

In [74]:
for i in range(len(X_test)):
    if select[i] == 1:
        Info.append(X_test[i])

In [75]:
#transform the data into orginal form
Info = count_vec.inverse_transform(Info)

In [76]:
type(Info)

list

In [78]:
After_tokenize = []

In [79]:
for i in Info:
    if list(i) != []:
        After_tokenize.append(list(i))

In [80]:
#after tokenize and refining all the words.
After_tokenize

[['function'],
 ['lambda'],
 ['java'],
 ['analysi', 'object'],
 ['databas'],
 ['sql'],
 ['code', 'tool'],
 ['git'],
 ['integr'],
 ['deliveri', 'develop', 'process'],
 ['framework'],
 ['transform'],
 ['analyt', 'report'],
 ['data', 'model'],
 ['standard'],
 ['code'],
 ['optim', 'solut'],
 ['access', 'data', 'servic'],
 ['data'],
 ['data', 'design', 'model', 'physic'],
 ['analyt', 'report', 'solut'],
 ['databas', 'physic'],
 ['integr'],
 ['experi'],
 ['data', 'model', 'physic'],
 ['architectur', 'data', 'enterpris'],
 ['data'],
 ['data', 'warehous'],
 ['data', 'mart'],
 ['model', 'tool'],
 ['tool'],
 ['master'],
 ['code'],
 ['java'],
 ['experi', 'program'],
 ['sql'],
 ['distribut', 'technolog'],
 ['store'],
 ['mysql'],
 ['oracl'],
 ['nosql', 'store'],
 ['big', 'queri'],
 ['distribut', 'engin', 'process'],
 ['apach', 'spark'],
 ['apach'],
 ['distribut'],
 ['apach'],
 ['aw'],
 ['gcp'],
 ['standard'],
 ['gcp'],
 ['azur'],
 ['aw'],
 ['cloud', 'platform', 'technolog'],
 ['cloud', 'experi'],
 ['experi', 'linux', 'program'],
 ['script'],
 ['ip'],
 ['architectur'],
 ['orchestr'],
 ['kubernet'],
 ['cloud'],
 ['servic'],
 ['vault'],
 ['api', 'gateway'],
 ['databas'],
 ['nosql', 'sql'],
 ['databas'],
 ['distribut'],
 ['cd'],
 ['github'],
 ['aw'],
 ['js'],
 ['api', 'tool'],
 ['program'],
 ['http'],
 ['redi'],
 ['cloud', 'experi'],
 ['experi', 'linux', 'program'],
 ['script'],
 ['ip'],
 ['architectur'],
 ['orchestr'],
 ['kubernet'],
 ['cloud'],
 ['servic'],
 ['vault'],
 ['api', 'gateway'],
 ['databas'],
 ['nosql', 'sql'],
 ['databas'],
 ['distribut'],
 ['cd'],
 ['github'],
 ['aw'],
 ['js'],
 ['api', 'tool'],
 ['program'],
 ['http'],
 ['redi'],
 ['web'],
 ['javascript'],
 ['html'],
 ['api', 'standard', 'ui', 'web'],
 ['framework', 'languag'],
 ['ui'],
 ['modul'],
 ['languag'],
 ['program'],
 ['program'],
 ['lambda'],
 ['knowledg'],
 ['knowledg'],
 ['architectur', 'consum', 'servic'],
 ['api'],
 ['applic'],
 ['ui', 'web'],
 ['design', 'javascript'],
 ['architectur'],
 ['eclips', 'netbean'],
 ['distribut', 'system'],
 ['contain', 'knowledg'],
 ['multi'],
 ['distribut'],
 ['nosql'],
 ['redi'],
 ['applic', 'java', 'server'],
 ['oracl'],
 ['tomcat'],
 ['framework'],
 ['cross'],
 ['chrome', 'dev', 'tool'],
 ['design', 'implement', 'respons'],
 ['audit', 'perform'],
 ['tune'],
 ['code', 'distribut', 'repositori'],
 ['git'],
 ['analyt'],
 ['expertis'],
 ['program'],
 ['framework'],
 ['api'],
 ['knowledg', 'sql'],
 ['line', 'linux'],
 ['object'],
 ['framework', 'ui'],
 ['design'],
 ['hadoop'],
 ['ai', 'framework'],
 ['databas', 'nosql'],
 ['contain', 'platform'],
 ['kubernet'],
 ['applic', 'benchmark'],
 ['optim'],
 ['applic', 'interfac', 'user'],
 ['analyt', 'devic'],
 ['control', 'measur'],
 ['applic', 'ui'],
 ['analyt', 'devic', 'medic'],
 ['interfac', 'program', 'user'],
 ['framework'],
 ['market'],
 ['embed', 'linux', 'system'],
 ['sql'],
 ['base', 'ip', 'network', 'protocol'],
 ['distribut', 'linux'],
 ['new', 'platform', 'product'],
 ['architect'],
 ['devop', 'engin'],
 ['architectur', 'best', 'design'],
 ['deploy'],
 ['scale'],
 ['architectur', 'direct'],
 ['platform'],
 ['deliveri', 'process'],
 ['extens'],
 ['extens', 'gener', 'next', 'web'],
 ['commerc', 'mobil', 'platform'],
 ['protocol', 'secur'],
 ['scale'],
 ['extens'],
 ['architectur', 'govern'],
 ['direct'],
 ['new', 'technolog'],
 ['domain', 'multipl', 'technolog'],
 ['technic'],
 ['busi'],
 ['code'],
 ['commerc'],
 ['busi', 'technic'],
 ['solut'],
 ['develop', 'lead', 'product'],
 ['architectur'],
 ['multi', 'transact'],
 ['nosql', 'store'],
 ['distribut', 'internet', 'scale', 'system'],
 ['go', 'java'],
 ['multi', 'perform', 'program'],
 ['product'],
 ['framework'],
 ['object', 'program'],
 ['fundament'],
 ['applic', 'develop', 'user', 'web'],
 ['code'],
 ['backend', 'servic'],
 ['js'],
 ['js'],
 ['dev', 'tool'],
 ['languag'],
 ['html'],
 ['platform', 'pre', 'process'],
 ['scss'],
 ['mysql'],
 ['data', 'model'],
 ['framework', 'test'],
 ['code', 'git', 'tool'],
 ['deploy'],
 ['standard'],
 ['design', 'detail'],
 ['architectur', 'develop'],
 ['specif'],
 ['technolog'],
 ['comput', 'program', 'technolog'],
 ['design', 'develop', 'experi', 'java'],
 ['base', 'solut'],
 ['expertis', 'technic'],
 ['program'],
 ['expertis', 'technic'],
 ['depart', 'program'],
 ['qualiti'],
 ['valid'],
 ['check', 'log', 'program'],
 ['program', 'specif'],
 ['program'],
 ['tool'],
 ['specif'],
 ['lead'],
 ['lead'],
 ['project', 'specif'],
 ['time', 'updat'],
 ['eac'],
 ['document'],
 ['databas', 'integr'],
 ['project'],
 ['sap'],
 ['program', 'specif'],
 ['safeti'],
 ['account'],
 ['budget', 'contract'],
 ['defin', 'xml'],
 ['guid'],
 ['lead'],
 ['protocol'],
 ['oper'],
 ['comput', 'master', 'scienc'],
 ['comput', 'scienc'],
 ['base', 'sa'],
 ['sa'],
 ['languag', 'sa'],
 ['commun', 'good', 'organiz'],
 ['data', 'detail', 'engin'],
 ['agil'],
 ['analysi', 'data', 'model'],
 ['deploy'],
 ['big', 'data', 'pipelin'],
 ['analyt', 'data'],
 ['data', 'pipelin'],
 ['analyt'],
 ['insight'],
 ['big', 'data', 'pipelin'],
 ['aw', 'technolog'],
 ['emr'],
 ['ec'],
 ['lambda'],
 ['event', 'new'],
 ['pipelin'],
 ['analyt', 'capabl'],
 ['capabl', 'real', 'time'],
 ['field'],
 ['dw', 'store'],
 ['aw', 'azur', 'cloud', 'googl', 'solut'],
 ['data', 'visual'],
 ['aw', 'hadoop', 'mapreduc'],
 ['emr'],
 ['apach', 'aw', 'spark'],
 ['analyt', 'platform', 'report'],
 ['api', 'data', 'experi', 'flexibl'],
 ['busi'],
 ['data', 'develop', 'softwar'],
 ['analyt', 'decis', 'model', 'predict'],
 ['data'],
 ['design'],
 ['agil', 'develop'],
 ['collabor'],
 ['applic', 'mobil'],
 ['fundament'],
 ['experi'],
 ['app'],
 ['app'],
 ['experi'],
 ['multi', 'optim', 'perform'],
 ['api'],
 ['code', 'tool'],
 ['git'],
 ['project'],
 ['expertis', 'technic'],
 ['softwar'],
 ['engin', 'softwar'],
 ['self'],
 ['master'],
 ['aw', 'azur', 'cloud', 'googl', 'platform'],
 ['linux'],
 ['window'],
 ['network'],
 ['databas'],
 ['aw'],
 ['azur'],
 ['gcp'],
 ['databas'],
 ['aw'],
 ['file', 'recoveri'],
 ['kubernet', 'servic'],
 ['aw'],
 ['comput', 'elast'],
 ['specif', 'technic'],
 ['effect'],
 ['activ', 'agil'],
 ['plan'],
 ['knowledg'],
 ['architectur', 'decis', 'key'],
 ['design'],
 ['detail'],
 ['master'],
 ['languag', 'object'],
 ['develop'],
 ['servic'],
 ['develop', 'experi', 'soa'],
 ['aw'],
 ['framework'],
 ['framework'],
 ['design', 'solid'],
 ['cloud', 'provid', 'public'],
 ['azur'],
 ['framework', 'java', 'script'],
 ['data', 'design', 'persist'],
 ['data', 'perform'],
 ['queri'],
 ['design', 'queri'],
 ['experi'],
 ['databas'],
 ['microsoft', 'server', 'sql'],
 ['db', 'non'],
 ['work'],
 ['agil'],
 ['function', 'technic'],
 ['optim', 'perform'],
 ['code'],
 ['analyt'],
 ['minim'],
 ['multipl'],
 ['fast'],
 ['knowledg'],
 ['busi', 'transform'],
 ['specif', 'technic'],
 ['devop', 'model'],
 ['case', 'gener', 'test'],
 ['architect'],
 ['api'],
 ['form'],
 ['develop'],
 ['studio'],
 ['android', 'platform'],
 ['app'],
 ['azur', 'integr'],
 ['activ', 'azur', 'directori'],
 ['notif'],
 ['app', 'center', 'studio', 'visual'],
 ['integr'],
 ['devop'],
 ['autom', 'test'],
 ['code', 'repositori'],
 ['git'],
 ['architectur'],
 ['agil'],
 ['app', 'cross', 'develop', 'platform'],
 ['lifecycl'],
 ['class'],
 ['cross', 'design', 'platform', 'ux'],
 ['api', 'hana', 'integr', 'sap'],
 ['form'],
 ['core', 'java'],
 ['fast'],
 ['self', 'work'],
 ['api'],
 ['crm'],
 ['api', 'clean', 'test'],
 ['api'],
 ['integr', 'salesforc'],
 ['function'],
 ['ux'],
 ['code'],
 ['document', 'intern', 'technic'],
 ['api'],
 ['data'],
 ['data', 'transform'],
 ['internet', 'softwar'],
 ['design', 'function', 'object'],
 ['infrastructur', 'platform'],
 ['devop'],
 ['framework'],
 ['infrastructur'],
 ['engin'],
 ['distribut', 'servic'],
 ['framework'],
 ['cach'],
 ['framework'],
 ['engin'],
 ['devop', 'site'],
 ['code'],
 ['document', 'intern', 'technic'],
 ['cloud', 'comput'],
 ['kubernet'],
 ['internet', 'softwar'],
 ['design', 'function', 'object'],
 ['api'],
 ['emerg', 'framework'],
 ['architectur'],
 ['cloud', 'industri', 'lead', 'provid'],
 ['aw'],
 ['azur'],
 ['gcp'],
 ['oper'],
 ['autom', 'deploy', 'pipelin'],
 ['collabor'],
 ['collabor', 'engin', 'product'],
 ['softwar'],
 ['api'],
 ['ui'],
 ['capabl', 'develop', 'softwar'],
 ['agil'],
 ['project'],
 ['emerg', 'technolog'],
 ['framework'],
 ['base', 'cloud'],
 ['valid'],
 ['script'],
 ['product'],
 ['api'],
 ['emerg', 'framework'],
 ['architectur'],
 ['cloud', 'industri', 'lead', 'provid'],
 ['aw'],
 ['azur'],
 ['gcp'],
 ['oper'],
 ['autom', 'deploy', 'pipelin'],
 ['collabor'],
 ['collabor', 'engin', 'product'],
 ['engin', 'softwar'],
 ['architect'],
 ['softwar'],
 ['api'],
 ['ui'],
 ['emerg', 'technolog'],
 ['framework'],
 ['base', 'cloud'],
 ['capabl', 'develop', 'softwar'],
 ['agil'],
 ['valid'],
 ['script'],
 ['product'],
 ['api'],
 ['emerg', 'framework'],
 ['architectur'],
 ['cloud', 'industri', 'lead', 'provid'],
 ['aw'],
 ['azur'],
 ['gcp'],
 ['oper'],
 ['autom', 'deploy', 'pipelin'],
 ['collabor'],
 ['collabor', 'engin', 'product'],
 ['softwar'],
 ['api'],
 ['ui'],
 ['capabl', 'develop', 'softwar'],
 ['agil'],
 ['project'],
 ['emerg', 'technolog'],
 ['framework'],
 ['base', 'cloud'],
 ['valid'],
 ['script'],
 ['product'],
 ['analysi', 'autom'],
 ['ui'],
 ['annot', 'data'],
 ['code'],
 ['cloud', 'comput'],
 ['analysi', 'autom'],
 ['annot'],
 ['advanc', 'data'],
 ['code'],
 ['catalogu'],
 ['project'],
 ['document'],
 ['file'],
 ['enhanc', 'product'],
 ['search'],
 ['intern'],
 ['base'],
 ['strategi', 'technic'],
 ['product'],
 ['technic'],
 ['commun'],
 ['escal'],
 ['devop'],
 ['self'],
 ['fast'],
 ['base', 'entri', 'knowledg'],
 ['portal'],
 ['time'],
 ['ip', 'knowledg'],
 ['firewal'],
 ['sso'],
 ['gateway'],
 ['experi'],
 ['configur'],
 ['linux'],
 ['base', 'system', 'window'],
 ['activ', 'directori', 'experi'],
 ['scenario'],
 ['protocol'],
 ['ip'],
 ['portal', 'tool'],
 ['master'],
 ['escal'],
 ['devop'],
 ['self'],
 ['fast'],
 ['base', 'entri', 'knowledg'],
 ['portal'],
 ['time'],
 ['ip', 'knowledg'],
 ['firewal'],
 ['sso'],
 ['gateway'],
 ['experi'],
 ['configur'],
 ['linux'],
 ['base', 'system', 'window'],
 ['activ', 'directori', 'experi'],
 ['scenario'],
 ['protocol'],
 ['ip'],
 ['portal', 'tool'],
 ['master'],
 ['advanc', 'sql'],
 ['process'],
 ['tool'],
 ['product', 'system'],
 ['learn'],
 ['spark'],
 ['kubernet'],
 ['aw'],
 ['autom', 'technolog'],
 ['kubernet'],
 ['system'],
 ['embed'],
 ['cyber', 'domain', 'inform', 'secur'],
 ['model'],
 ['analysi', 'data'],
 ['data', 'set', 'synthet'],
 ['learn', 'machin', 'model'],
 ['enhanc', 'softwar'],
 ['comput', 'internet', 'network', 'program'],
 ['document'],
 ['product', 'project'],
 ['cycl', 'life'],
 ['assess'],
 ['intern', 'specif'],
 ['manual'],
 ['plan', 'test'],
 ['script'],
 ['code'],
 ['develop', 'experi', 'java'],
 ['agil'],
 ['develop', 'framework', 'languag', 'tool'],
 ['architectur', 'servic'],
 ['contain'],
 ['orchestr', 'tool'],
 ['azur'],
 ['kubernet'],
 ['openshift'],
 ['cluster'],
 ['deploy', 'servic'],
 ['framework', 'tool'],
 ['api', 'gateway'],
 ['servic'],
 ['data'],
 ['integr'],
 ['code'],
 ['git'],
 ['bitbucket'],
 ['framework', 'test'],
 ['applic', 'server'],
 ['webspher'],
 ['tomcat'],
 ['databas', 'server'],
 ['oracl'],
 ['linux'],
 ['knowledg', 'object', 'program'],
 ['script'],
 ['apach'],
 ['apach'],
 ['eclips'],
 ['xml'],
 ['apach'],
 ['bash', 'linux', 'script'],
 ['sql'],
 ['java', 'messag', 'servic'],
 ['technolog'],
 ['javascript'],
 ['api'],
 ['backend', 'servic'],
 ['javascript', 'technolog'],
 ['agil', 'collabor'],
 ['softwar'],
 ['api', 'develop'],
 ['git'],
 ['github'],
 ['databas'],
 ['mysql'],
 ['framework', 'test'],
 ['tool'],
 ['cach', 'strategi'],
 ['api'],
 ['api'],
 ['gcp'],
 ['kubernet'],
 ['javascript'],
 ['technolog'],
 ['api'],
 ['backend', 'servic'],
 ['javascript', 'technolog'],
 ['agil', 'collabor'],
 ['softwar'],
 ['api', 'develop'],
 ['git'],
 ['github'],
 ['databas'],
 ['mysql'],
 ['framework', 'test'],
 ['tool'],
 ['cach', 'strategi'],
 ['api'],
 ['api'],
 ['gcp'],
 ['kubernet'],
 ['javascript'],
 ['technolog'],
 ['javascript'],
 ['api'],
 ['backend', 'servic'],
 ['javascript', 'technolog'],
 ['agil', 'collabor'],
 ['softwar'],
 ['api', 'develop'],
 ['git'],
 ['github'],
 ['databas'],
 ['mysql'],
 ['framework', 'test'],
 ['tool'],
 ['cach', 'strategi'],
 ['api'],
 ['api'],
 ['gcp'],
 ['kubernet'],
 ['javascript'],
 ['technolog'],
 ['api'],
 ['backend', 'servic'],
 ['javascript', 'technolog'],
 ['agil', 'collabor'],
 ['softwar'],
 ['api', 'develop'],
 ['git'],
 ['github'],
 ['databas'],
 ['mysql'],
 ['framework', 'test'],
 ['tool'],
 ['cach', 'strategi'],
 ['api'],
 ['api'],
 ['gcp'],
 ['kubernet'],
 ['javascript'],
 ['analyt', 'new', 'product'],
 ['java'],
 ['deploy'],
 ['configur'],
 ['backend', 'system'],
 ['webservic'],
 ['sql'],
 ['databas'],
 ['mysql'],
 ['databas', 'time'],
 ['document'],
 ['framework'],
 ['kubernet'],
 ['program'],
 ['design'],
 ['java', 'script'],
 ['chang', 'ui'],
 ['design', 'specif'],
 ['coordin'],
 ['ui'],
 ['ux'],
 ['ui'],
 ['html'],
 ['javascript'],
 ['ui'],
 ['backend', 'servic'],
 ['respons', 'web'],
 ['html'],
 ['framework', 'ui'],
 ['applic',
  'custom',
  'develop',
  'implement',
  'mobil',
  'softwar',
  'system',
  'web'],
 ['multipl', 'technic'],
 ['devop'],
 ['base', 'interfac', 'respons', 'user', 'web'],
 ['js'],
 ['html'],
 ['javascript'],
 ['api'],
 ['integr'],
 ['autom', 'suit', 'test'],
 ['ux'],
 ['experi'],
 ['tool'],
 ['deploy', 'dev', 'op', 'process'],
 ['document'],
 ['engin'],
 ['design'],
 ['experi'],
 ['api'],
 ['dev', 'line'],
 ['servic'],
 ['gcp'],
 ['aw'],
 ['javascript'],
 ['script'],
 ['bash'],
 ['databas', 'distribut', 'system'],
 ['ms'],
 ['kubernet'],
 ['api', 'system'],
 ['git'],
 ['perform'],
 ['js'],
 ['interfac', 'user'],
 ['android', 'java'],
 ['android', 'kotlin'],
 ['engin', 'experi', 'softwar'],
 ['code', 'design', 'secur'],
 ['identifi'],
 ['integr'],
 ['deploy'],
 ['new'],
 ['advanc', 'languag', 'object'],
 ['commun'],
 ['backend', 'develop', 'experi'],
 ['servic'],
 ['aw', 'technolog'],
 ['kubernet'],
 ['platform'],
 ['applic', 'persist', 'system'],
 ['databas', 'nosql', 'sql'],
 ['autom'],
 ['deploy', 'process'],
 ['time'],
 ['incid', 'infrastructur'],
 ['aw', 'azur', 'gcp'],
 ['system'],
 ['databas', 'nosql'],
 ['broker', 'event'],
 ['api', 'gateway'],
 ['function', 'gcp', 'lambda'],
 ['commun'],
 ['open', 'sourc'],
 ['architectur'],
 ['api', 'core'],
 ['experi'],
 ['offer', 'open', 'sourc'],
 ['autom', 'infrastructur', 'tool'],
 ['custom'],
 ['commun'],
 ['lifecycl'],
 ['go', 'languag', 'program'],
 ['ph'],
 ['framework'],
 ['data'],
 ['network'],
 ['framework', 'learn', 'one', 'softwar'],
 ['network'],
 ['network'],
 ['http'],
 ['ip'],
 ['devic'],
 ['server'],
 ['firewal'],
 ['commun'],
 ['iot'],
 ['industri'],
 ['aw', 'plu'],
 ['azur', 'microsoft'],
 ['api'],
 ['code', 'languag'],
 ['linux', 'system'],
 ['experi'],
 ['inform'],
 ['good'],
 ['constraint', 'oper'],
 ['framework'],
 ['data'],
 ['network'],
 ['learn'],
 ['domain', 'new'],
 ['commun'],
 ['framework', 'one', 'softwar'],
 ['hadoop'],
 ['languag'],
 ['custom'],
 ['busi'],
 ['netsuit'],
 ['erp', 'implement', 'netsuit'],
 ['integr', 'system'],
 ['processor'],
 ['bank', 'electron', 'transfer'],
 ['crm'],
 ['system'],
 ['bill'],
 ['solut'],
 ['enhanc'],
 ['function'],
 ['valid'],
 ['configur', 'new'],
 ['optim'],
 ['document'],
 ['erp'],
 ['oracl'],
 ['netsuit'],
 ['autom'],
 ['optim', 'system'],
 ['erp', 'experi', 'netsuit'],
 ['fundament', 'integr', 'system'],
 ['integr', 'product'],
 ['erp', 'system'],
 ['com', 'salesforc'],
 ['processor'],
 ['sql'],
 ['javascript'],
 ['script', 'set', 'tool'],
 ['servic', 'web'],
 ['provis', 'user'],
 ['analyt', 'schedul', 'script'],
 ['multi'],
 ['commun'],
 ['saa'],
 ['base', 'busi'],
 ['administr', 'netsuit'],
 ['master'],
 ['erp', 'experi', 'implement'],
 ['custom'],
 ['network'],
 ['autom', 'test'],
 ['standard'],
 ['system'],
 ['commun', 'platform', 'scale'],
 ['api', 'gateway'],
 ['servic'],
 ['develop', 'javascript'],
 ['js'],
 ['messag'],
 ['api'],
 ['cloud'],
 ['app', 'develop', 'web'],
 ['ui'],
 ['api', 'experi', 'gateway'],
 ['cd', 'technolog'],
 ['workflow'],
 ['applic', 'real', 'time'],
 ['solut', 'standard'],
 ['cloud'],
 ['autom', 'orchestr', 'pipelin'],
 ['contain', 'manag', 'vm'],
 ['program'],
 ['cloud'],
 ['gcp'],
 ['aw'],
 ['azur'],
 ['js'],
 ['gcp'],
 ['kubernet'],
 ['code', 'express'],
 ['provis'],
 ['applic', 'lifecycl', 'view'],
 ['function', 'program'],
 ['architectur', 'clean', 'code'],
 ['good'],
 ['commun'],
 ['matur'],
 ['knowledg', 'learn'],
 ['experi', 'kotlin'],
 ['autom', 'mobil', 'test'],
 ['cd', 'workflow'],
 ['applic', 'live'],
 ['backend', 'experi'],
 ['git'],
 ['github'],
 ['bitbucket'],
 ['android', 'kotlin'],
 ['code', 'express', 'kotlin'],
 ['android', 'sdk'],
 ['android', 'applic', 'lifecycl', 'view'],
 ['function', 'program'],
 ['architectur', 'clean', 'code'],
 ['good'],
 ['commun', 'good'],
 ['matur'],
 ['experi', 'kotlin'],
 ['autom', 'mobil', 'test'],
 ['cd', 'workflow'],
 ['backend', 'experi'],
 ['git'],
 ['github'],
 ['bitbucket'],
 ['android', 'kotlin'],
 ['code', 'express', 'kotlin'],
 ['android', 'sdk'],
 ['android', 'applic', 'lifecycl', 'view'],
 ['function', 'program'],
 ['architectur', 'clean', 'code'],
 ['good'],
 ['commun', 'good'],
 ['matur'],
 ['experi', 'kotlin'],
 ['autom', 'mobil', 'test'],
 ['cd', 'workflow'],
 ['backend', 'experi'],
 ['git'],
 ['github'],
 ['bitbucket'],
 ['cross', 'function'],
 ['design', 'simpl'],
 ['analyt'],
 ['architectur', 'servic'],
 ['autom', 'control'],
 ['aw', 'experi', 'linux', 'network'],
 ['contain', 'platform'],
 ['kubernet'],
 ['autom', 'system'],
 ['go', 'kotlin'],
 ['network', 'perform'],
 ['network', 'optim'],
 ['protocol', 'real', 'time', 'transact'],
 ['http'],
 ['network', 'sniffer'],
 ['protocol'],
 ['ip'],
 ['comput', 'platform'],
 ['oper'],
 ['comput', 'infrastructur', 'platform'],
 ['self', 'servic', 'tool'],
 ['provis'],
 ['aw'],
 ['cloud', 'vendor'],
 ['kubernet'],
 ['kubernet'],
 ['comput', 'infrastructur'],
 ['infrastructur', 'new'],
 ['infrastructur', 'migrat'],
 ['kubernet'],
 ['aw', 'infrastructur'],
 ['monitor', 'system'],
 ['aw', 'experi', 'linux'],
 ['autom', 'system'],
 ['new', 'product'],
 ['data', 'pipelin', 'process', 'real', 'time'],
 ['framework'],
 ['data', 'process', 'system'],
 ['mapreduc'],
 ['spark'],
 ['analyt', 'data', 'scienc'],
 ['infrastructur'],
 ['data', 'process', 'system'],
 ['databas', 'nosql'],
 ['data', 'solut', 'warehous'],
 ['autom', 'consul', 'tool'],
 ...]